// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB61NDEbvPn8aKL9v13EO5OpcyO7wCRYwE',
    appId: '1:60045342574:web:b38bbd6e4a90fc3452f37f',
    messagingSenderId: '60045342574',
    projectId: 'personal-portfolio-ab350',
    authDomain: 'personal-portfolio-ab350.firebaseapp.com',
    storageBucket: 'personal-portfolio-ab350.appspot.com',
    measurementId: 'G-QB6ECTSSXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN33dblADY5ytf0N_XW4ic0-Mb8wglPb0',
    appId: '1:60045342574:android:86eb69f6c37f996952f37f',
    messagingSenderId: '60045342574',
    projectId: 'personal-portfolio-ab350',
    storageBucket: 'personal-portfolio-ab350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUriAlvuE06781OgtvOXu0KeK8Or281j8',
    appId: '1:60045342574:ios:ce18ca90b80e775d52f37f',
    messagingSenderId: '60045342574',
    projectId: 'personal-portfolio-ab350',
    storageBucket: 'personal-portfolio-ab350.appspot.com',
    iosClientId: '60045342574-2504oog8q97mbj9cnod02dhp04eke45c.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUriAlvuE06781OgtvOXu0KeK8Or281j8',
    appId: '1:60045342574:ios:ce18ca90b80e775d52f37f',
    messagingSenderId: '60045342574',
    projectId: 'personal-portfolio-ab350',
    storageBucket: 'personal-portfolio-ab350.appspot.com',
    iosClientId: '60045342574-2504oog8q97mbj9cnod02dhp04eke45c.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalPortfolio',
  );
}
